# Generated by Django 4.0.4 on 2022-09-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'car',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Car_model',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'car_model',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cars_category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'category_cars',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dukanlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ady', models.CharField(max_length=150)),
                ('welayat', models.CharField(max_length=15)),
                ('salgy', models.CharField(max_length=255)),
                ('tel1', models.CharField(max_length=15)),
                ('tel2', models.CharField(max_length=15)),
                ('geo', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'dukanlar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zapcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('priceman', models.FloatField(db_column='priceMan')),
                ('notes', models.CharField(max_length=255)),
                ('carids', models.CharField(db_column='carIds', max_length=255)),
                ('catid', models.CharField(db_column='catId', max_length=255)),
                ('yagday', models.IntegerField(default=0)),
                ('tel', models.CharField(default=99363370891, max_length=100)),
            ],
            options={
                'db_table': 'zapcas',
                'managed': False,
            },
        ),
    ]
